version: 2.1

jobs:
  lint:
    working_directory: ~/repo
    docker:
      - image: csabasulyok/pnpm:14.17.6-alpine
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: pnpm i
      - run:
          name: Run linters
          command: pnpm lint

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths:
            - "."
  
workflows:
  lint:
    jobs:
      - lint

              